version: '3.3'
services:
  web:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes: 
      - '$PWD/website:/var/www/html'
    depends_on:
      - api
    ports:
      - "8081:5001"
  api:
    image: python:2.7-stretch
    volumes:
      - '$PWD/student_age.json:/data/student_age.json'
    ports:
      - "8082:5000"
